baseURL = 'https://momzw.github.io/webpage/'
languageCode = 'en-us'
title = 'My Personal Webpage'
theme = 'personal-web'
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
    main = "Hi, I'm Moritz :wave:"
    sub = "I'm a PhD student at the University of Bern"

[params.main]
    latestPublishHeader = "My Latest Project"

[taxonomies]
    design = "designs"
    tech = "techs"

[blackfriday]
    hrefTargetBlank = true

[params]
    breadcrumb = true
    accentColor = "#FD3519"
    mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
    rendererSafe = true # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
    gopher = "/images/gopher.jpg" # checkout https://gopherize.me/
    h1 = 'Bummer!'
    p = "It seems that this page doesn't exist."

[params.sidebar]
    backgroundImage = 'images/planet-moon.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
    gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
    logo = "images/portrait.jpg" # - default "/images/edna-west.jpg"

[params.assets]
    favicon = ""
    customCSS = ""

[params.social]
    github = "https://github.com/momzw"

[params.contact]
    email = "moritzmzw@gmail.com"
    text= "Mail me!" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
    identifier = "about"
    name = "About"
    title = "About section"
    url = "/about/"
    weight = -130

[[menu.main]]
    identifier = "cv"
    name = "CV"
    title = "Curriculum Vitae"
    url = "/cv/"
    weight = -120


[[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    title = "Portfolio"
    url = "/portfolio/"
    weight = -110

[[menu.main]]
    identifier = "post"
    name = "Posts"
    title = "Posts section"
    url = "/post/"
    weight = -100

[[menu.main]]
    identifier = "solar"
    name = "Solar Machine Learning"
    title = "Solar section"
    url = "/solar-flare-forecasting"
    weight = -90


[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true